### ISSUE TITLE
Master - Fix Ghost message bug

### ISSUE THREAD

**Issue by Berrescuda** [BenningtonCS/GFS#98] opened 2013-11-14 00:49 UTC
The master routinely receives an empty string, apparently from nowhere, someone should hunt this down and fix it.

**Comment by edaniszewski** [comment] 2013-11-14 06:10
@Kgespada 's commit e47f774a7a9696cd62d6c0130f9e9eefb1643e90 addresses this. Instead of having the thread crash now, it will end gracefully. 

The ghost message still exists, however. I have a feeling it resides in either functionLibrary.recv() or functionLibrary.send()

#72 -- See Andrew's comment about acks.. they may be unnecessary here, and they may be the cause of/contribute to the problem.

**Comment by edaniszewski** [comment] 2013-11-16 02:38
This issue has been resolved with issue #105  

after running tests I no longer see the ghost messages.

**Closed as completed by edaniszewski** 2013-11-16 02:38 UTC
